const coreNameList = [
  "Aadrita Siva",
  "Aarav Arora",
  "Adi Gulalkari",
  "Anshul Kumar",
  "Arnav Bahuguna",
  "Aryaman Anand",
  "Ashish G Hallur",
  "Dhruv Rajeshkumar Shah",
  "Divina Pooja John",
  "Harsh Vardhan Shukla",
  "Hitarth Kotecha",
  "Ishaan Kishore Mathur",
  "Jeenia Gogoi",
  "Kaushal Vishnukanth Rathi",
  "Kushagra Gupta",
  "Lanka Vasanth",
  "Laxmi Brunda Dogiparthy",
  "Munawwar Abdul Muneer",
  "Nischay Sinha",
  "Puja Balasundaram",
  "Purbashree Bhattacharyya",
  "Raghul Gunasekar",
  "Ravin D",
  "Rohan Khatua",
  "Rohith Parahmesh K",
  "Rudrank Basant",
  "Sai Sahith Goud Bonugala",
  "Shaan Chandra",
  "Shalini Dasararaju",
  "Shivam Sharma K",
  "Shreya Mangal",
  "Shreyas Nirgunde",
  "Shubh Bansal",
  "Soha Jagtap",
  "Soosan Shabnam",
  "Sreejita Hazra",
  "Sriram S",
  "Tavishi Jain",
  "Vaibhavi Jha",
  "Varun Gupta",
  "Varun Sudhir",
  "Yashaswini Shivathaya",
  "Zeeshan Afzal",
];

export default coreNameList;
